### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by aloraps** [MunyDev/TeaVM-lwjgl-port#15]
Hello, I'd like to inquire further regarding this project and a potential business opportunity for you (very closely related to this -- using a LWJGL implementation with TeaVM port).

If interested, please add my Discord: alora.io

**Comment by MunyDev** [comment]
We can't do this business oppurtunity, I was going to tell you on discord, but you weren't accepting friend requests. If you have any questions (or bugs) about this project, please ask them on discord through the username @unretained.
